<?php
 return array (
  'app_name' => 'Laravel',
  'app_env' => 0,
  'app_debug' => 0,
  'app_url' => 'http://eric.com',
  'cdn_url' => 'http://cdn-eric.com',
  'throttle' => '15,0.2',
  'google_index' => '1',
  'default_meta_title' => 'Laravel',
  'default_meta_description' => 'https://github.com/faridsh69/cms is this cms github.',
  'default_meta_image' => '//cdn-eric.com/storage/photos/shares/download_cropped_1558181319.png',
  'default_user_image' => '/cdn/upload/images/user.png',
  'logo' => '/cdn/upload/images/logo.png',
  'pagination_number' => '10',
  'crisp' => 'Afsadfasdf',
  'google_analytics' => 'sdfsdfasdf',
  'contact' => 
  array (
    'phone' => '+100000000',
    'mobile' => '+190000000',
    'email' => 'farid.sh69@gmail.com',
    'fax' => '+130000000',
    'address' => 'US, California, ....',
    'telegram' => 'telegram_id',
    'instagram' => 'instagram_id',
    'skype' => 'skype_id',
    'facebook' => 'facebook_id',
    'twitter' => 'twitter_id',
    'google' => 'gplus_id',
  ),
  'MAIL_USERNAME' => 'farid.sh69@gmail.com',
  'MAIL_PASSWORD' => 'faridSag123@',
  'MAIL_FROM_ADDRESS' => 'farid.sh69@gmail.com',
  'MAIL_FROM_NAME' => 'CMS',
  'GOOGLE_CLIENT_ID' => '257230142631-gdvd9gh8vfj67p732hek6t4tcpagd59d.apps.googleusercontent.com',
  'GOOGLE_CLIENT_SECRET' => 'fpiyJN82Lb3Y_8CGKevGB8Ri',
  'GOOGLE_CLIENT_CALLBACK' => 'http://eric.com/login/google/callback',
) ;