<?php
 return array (
  'app_name' => 'Laravel',
  'app_env' => 0,
  'app_debug' => 0,
  'app_url' => 'http://eric.com',
  'cdn_url' => 'http://cdn-eric.com',
  'throttle' => '15,0.2',
  'google_index' => '1',
  'default_meta_title' => 'Laravel',
  'default_meta_description' => 'https://github.com/faridsh69/cms is this cms github.',
  'default_meta_image' => '//cdn-eric.com/storage/photos/shares/download_cropped_1558181319.png',
  'default_user_image' => '/cdn/upload/images/user.png',
  'logo' => '/cdn/upload/images/logo.png',
  'pagination_number' => '10',
  'crisp' => 'Afsadfasdf',
  'google_analytics' => 'sdfsdfasdf',
  'mail_username' => 'farid.sh69@gmail.com',
  'mail_password' => 'farid111111',
  'mail_from_address' => 'farid.sh69@gmail.com',
  'mail_from_name' => 'CMS',
  'google_client_id' => '257230142631-gdvd9gh8vfj67p732hek6t4tcpagd59d.apps.googleusercontent.com',
  'google_client_secret' => 'fpiyJN82Lb3Y_8CGKevGB8Ri',
  'google_client_callback' => 'http://eric.com/login/google/callback',
) ;