<?php

declare(strict_types=1);

$cms = [
	'config' => [
		'models_namespace' => 'App\Models\\',
		'faker_files' => '/app/public/static-files/faker/',
		'cms_files' => '/app/public/static-files/laravel-cms-website/',
		'default_images' => '/storage/static-files/default-model-images/',
		'upload_folder' => '/upload/',
		'cache_time' => 1,
	],
	'migration' => [
		'user',
		'category',
		'activity',
		'address',
		'advertise',
		'basket',
		'block',
		'blog',
		'car',
		'cinema',
		'comment',
		'factor',
		'field',
		'file',
		'follow',
		'food',
		'food-program',
		'form',
		'answer',
		'gym',
		'gym-action',
		'gym-program',
		'home',
		'hotel',
		'like',
		'module',
		'movie',
		'music',
		'notification',
		'page',
		'post',
		'product',
		'rate',
		'restaurant',
		'setting-general',
		'setting-contact',
		'setting-developer',
		'shop',
		'showtime',
		'story',
		'tag',
		'tagend',
		'tour',
		'travel',
	],
	'seeder' => [
		'address',
		'advertise',
		'answer',
		'blog',
		'category',
		'factor',
		'field',
		'food',
		'form',
		'restaurant',
		'tag',
		'tagend',
	],
	'policies' => [
		'activity',
		'advertise',
		'answer',
		'address',
		'block',
		'blog',
		'car',
		'category',
		'cinema',
		'comment',
		'factor',
		'field',
		'file',
		'follow',
		'food',
		'food-program',
		'form',
		'gym',
		'gym-action',
		'gym-program',
		'home',
		'hotel',
		'like',
		'module',
		'movie',
		'music',
		'notification',
		'page',
		'permission',
		'post',
		'product',
		'rate',
		'restaurant',
		'role',
		'shop',
		'showtime',
		'story',
		'tag',
		'tagend',
		'tour',
		'travel',
		'user',
	],
	'admin_routes' => [
		'activity',
		'address',
		'answer',
		'block',
		'blog',
		'category',
		'comment',
		'factor',
		'field',
		'file',
		'follow',
		'food',
		'form',
		'like',
		'module',
		'notification',
		'page',
		'permission',
		'post',
		'product',
		'rate',
		'restaurant',
		'role',
		'tag',
		'tagend',
		'user',
	],
	'admin_tests' => [
		'address',
		'answer',
		'block',
		'blog',
		'category',
		'comment',
		'factor',
		'field',
		'file',
		'follow',
		'food',
		'form',
		'like',
		'module',
		'page',
		'post',
		'product',
		'rate',
		'restaurant',
		'tag',
		'tagend',
		'user',
	],
	'front_routes' => ['blog', 'category', 'food', 'tag', 'user'],
	'front_tests' => ['blog', 'category', 'food', 'tag', 'user'],
	'api_routes' => [
		'blog',
		'category',
		'food',
		'tag',
		'user',
		// 'address',
		// 'advertise',
		// 'car',
		// 'cinema',
		// 'food',
		// 'food-program',
		// 'gym',
		// 'gym-action',
		// 'gym-program',
		// 'home',
		// 'hotel',
		// 'movie',
		// 'music',
		// 'post',
		// 'product',
		// 'restaurant',
		// 'shop',
		// 'showtime',
		// 'story',
		// 'tour',
		// 'travel',
	],
	'api_tests' => ['blog', 'category', 'food', 'tag', 'user'],
	'default_columns' => [
		'title' => [
			'name' => 'title',
			'type' => 'string',
			'database' => '',
			'rule' => 'required',
			'help' => 'Title should be unique.',
			'form_type' => '',
			'table' => true,
		],
		'description' => [
			'name' => 'description',
			'type' => 'text',
			'database' => 'nullable',
			'rule' => 'nullable',
			'help' => 'Description should be 50 - 70 characters, maximum 160 characters.',
			'form_type' => 'textarea',
			'table' => true,
		],
		'content' => [
			'name' => 'content',
			'type' => 'text',
			'database' => 'nullable',
			'rule' => 'nullable',
			'help' => '',
			'form_type' => 'ckeditor',
			'table' => false,
		],
		'url' => [
			'name' => 'url',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => 'nullable',
			'help' => 'Url should be unique, contain [a-z, 0-9, -], required for seo',
			'form_type' => '',
			'table' => false,
		],
		'keywords' => [
			'name' => 'keywords',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => 'nullable|max:191',
			'help' => 'Keywords is optional and is not important for google',
			'form_type' => '',
			'table' => false,
		],
		'activated' => [
			'name' => 'activated',
			'type' => 'boolean',
			'database' => 'default',
			'rule' => 'boolean',
			'help' => '',
			'form_type' => 'switch-m', // switch-m, checkbox-m, switch-bootstrap-m
			'table' => false,
		],
		'google_index' => [
			'name' => 'google_index',
			'type' => 'boolean',
			'database' => 'default',
			'rule' => 'boolean',
			'help' => 'Shows google robots will follow this link.',
			'form_type' => 'checkbox-m',
			'table' => false,
		],
		'canonical_url' => [
			'name' => 'canonical_url',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => 'nullable|max:191',
			'help' => 'Canonical url is neccessary if one content will show from two different urls.',
			'form_type' => '',
			'table' => false,
		],
		'icon' => [
			'name' => 'icon',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => '',
			'help' => 'Click: <a target="blank" href="/admin/icon/list">List of Icons</a> - for example: fa-glass',
			'form_type' => '',
			'table' => false,
		],
		'full_name' => [
			'name' => 'full_name',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => '',
			'table' => false,
		],
		'user_id' => [
			'name' => 'user_id',
			'type' => 'unsignedBigInteger',
			'database' => 'nullable',
			'relation' => 'users',
			'rule' => 'nullable|exists:users,id',
			'help' => '',
			'form_type' => 'entity',
			'class' => 'App\Models\User',
			'property' => 'email',
			'property_key' => 'id',
			'multiple' => false,
			'table' => true,
		],
		'category_id' => [
			'name' => 'category_id',
			'type' => 'unsignedBigInteger',
			'database' => 'nullable',
			'relation' => 'categories',
			'rule' => 'nullable|exists:categories,id',
			'help' => '',
			'form_type' => 'entity',
			'class' => 'App\Models\Category',
			'property' => 'title',
			'property_key' => 'id',
			'query_builder' => 'type',
			'multiple' => false,
			'table' => true,
		],
		'tags' => [
			'name' => 'tags',
			'type' => 'array',
			'database' => 'none',
			'rule' => 'nullable',
			'help' => '',
			'form_type' => 'entity',
			'class' => 'App\Models\Tag',
			'property' => 'title',
			'property_key' => 'id',
			'query_builder' => 'type',
			'multiple' => true,
			'table' => false,
		],
		'relateds' => [
			'name' => 'relateds',
			'type' => 'array',
			'database' => 'none',
			'rule' => 'nullable',
			'help' => 'Select related items to suggest to user.',
			'form_type' => 'entity',
			'property' => 'title',
			'property_key' => 'id',
			'multiple' => true,
			'table' => false,
		],
		'language' => [
			'name' => 'language',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => '',
			'help' => 'Specify language.',
			'form_type' => 'enum',
			'form_enum_class' => 'AppLanguage',
			'table' => false,
		],
		'order' => [
			'name' => 'order',
			'type' => 'integer',
			'database' => 'nullable',
			'rule' => 'nullable|numeric',
			'help' => 'Sort by this column, lower order will be ahead',
			'form_type' => '',
			'table' => false,
		],
		'image' => [
			'name' => 'image',
			'type' => 'file',
			'database' => 'none',
			'rule' => 'nullable',
			'help' => 'You can choose multiple images',
			'form_type' => 'file',
			'file_accept' => 'image/*',
			'file_multiple' => true,
			'table' => true,
		],
		'video' => [
			'name' => 'video',
			'type' => 'file',
			'database' => 'none',
			'rule' => 'nullable',
			'help' => 'You can choose multiple videos',
			'form_type' => 'file',
			'file_accept' => 'video/*',
			'file_multiple' => true,
			'table' => false,
		],
		'document' => [
			'name' => 'document',
			'type' => 'file',
			'database' => 'none',
			'rule' => 'nullable',
			'help' => 'You can choose multiple documents',
			'form_type' => 'file',
			'file_accept' => '*',
			'file_multiple' => true,
			'table' => false,
		],
		'audio' => [
			'name' => 'audio',
			'type' => 'file',
			'database' => 'none',
			'rule' => 'nullable',
			'help' => 'You can choose multiple videos',
			'form_type' => 'file',
			'file_accept' => 'audio/*',
			'file_multiple' => true,
			'table' => false,
		],
		'opening_hours' => [
			'name' => 'opening_hours',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => 'nullable|max:191',
			'help' => '',
			'form_type' => '',
			'table' => false,
		],
		'city' => [
			'name' => 'city',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => 'nullable|max:191',
			'help' => '',
			'form_type' => '',
			'table' => false,
		],
		'country' => [
			'name' => 'country',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => '',
			'table' => false,
		],
		'province' => [
			'name' => 'province',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => '',
			'table' => false,
		],
		'city' => [
			'name' => 'city',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => '',
			'table' => true,
		],
		'address' => [
			'name' => 'address',
			'type' => 'text',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => 'textarea',
			'table' => true,
		],
		'postal_code' => [
			'name' => 'postal_code',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => '',
			'table' => false,
		],
		'phone' => [
			'name' => 'phone',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => 'nullable|numeric',
			'help' => 'International format +4917...',
			'form_type' => 'phone',
			'table' => true,
		],
		'telephone' => [
			'name' => 'telephone',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => 'nullable|max:30',
			'help' => 'Home Number',
			'form_type' => '',
			'table' => false,
		],
		'latitude' => [
			'name' => 'latitude',
			'type' => 'decimal',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => '',
			'table' => false,
		],
		'longitude' => [
			'name' => 'longitude',
			'type' => 'decimal',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => '',
			'table' => false,
		],
		'properties' => [
			'name' => 'properties',
			'type' => 'text',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => 'textarea',
			'table' => false,
		],
		'website' => [
			'name' => 'website',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => 'nullable',
			'help' => '',
			'form_type' => '',
			'table' => false,
		],
		'email' => [
			'name' => 'email',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => 'nullable',
			'help' => 'Wrtie valid email address',
			'form_type' => 'email',
			'table' => true,
		],
		'price' => [
			'name' => 'price',
			'type' => 'bigInteger',
			'database' => 'nullable',
			'rule' => 'nullable|numeric',
			'help' => '',
			'form_type' => 'number',
			'table' => true,
		],
		'discount_price' => [
			'name' => 'discount_price',
			'type' => 'bigInteger',
			'database' => 'nullable',
			'rule' => 'nullable|numeric',
			'help' => '',
			'form_type' => 'number',
			'table' => false,
		],
		'year' => [
			'name' => 'year',
			'type' => 'integer',
			'database' => 'nullable',
			'rule' => 'nullable|numeric',
			'help' => '',
			'form_type' => 'number',
			'table' => false,
		],
		'rooms' => [
			'name' => 'rooms',
			'type' => 'integer',
			'database' => 'nullable',
			'rule' => 'nullable|numeric',
			'help' => '',
			'form_type' => 'number',
			'table' => true,
		],
		'color' => [
			'name' => 'color',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => '',
			'table' => false,
		],
		'foundation' => [
			'name' => 'foundation',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => '',
			'table' => true,
		],
		'calorie' => [
			'name' => 'calorie',
			'type' => 'integer',
			'database' => 'nullable',
			'rule' => 'nullable|numeric',
			'help' => '',
			'form_type' => '',
			'table' => false,
		],
		'singer' => [
			'name' => 'singer',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => '',
			'table' => true,
		],
		'director' => [
			'name' => 'director',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => '',
			'table' => true,
		],
		'date' => [
			'name' => 'date',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => 'date',
			'table' => true,
		],
		'time' => [
			'name' => 'time',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => 'time',
			'table' => true,
		],
		'destination' => [
			'name' => 'destination',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => '',
			'table' => true,
		],
		'origin' => [
			'name' => 'origin',
			'type' => 'string',
			'database' => 'nullable',
			'rule' => '',
			'help' => '',
			'form_type' => '',
			'table' => true,
		],
	],
];

$cms['social_companies'] = ['GOOGLE', 'TWITTER', 'FACEBOOK', 'LINKEDIN', 'GITHUB', 'GITLAB', 'BITBUCKET'];

foreach ($cms['social_companies'] as $social_company) {
	$cms[mb_strtolower($social_company)] = [
		'client_id' => env($social_company . '_CLIENT_ID'),
		'client_secret' => env($social_company . '_CLIENT_SECRET'),
		'redirect' => env($social_company . '_CLIENT_CALLBACK'),
	];
}

return $cms;
