<?php

$output = [
    'mailgun' => [
        'domain' => env('MAILGUN_DOMAIN'),
        'secret' => env('MAILGUN_SECRET'),
        'endpoint' => env('MAILGUN_ENDPOINT', 'api.mailgun.net'),
    ],

    'postmark' => [
        'token' => env('POSTMARK_TOKEN'),
    ],

    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

    'sparkpost' => [
        'secret' => env('SPARKPOST_SECRET'),
    ],

    'stripe' => [
        'model' => App\Models\User::class,
        'key' => env('STRIPE_KEY'),
        'secret' => env('STRIPE_SECRET'),
        'webhook' => [
            'secret' => env('STRIPE_WEBHOOK_SECRET'),
            'tolerance' => env('STRIPE_WEBHOOK_TOLERANCE', 300),
        ],
    ],
    // 'rules' => [
    //     'title' => 'required|max:60|min:5|unique:blogs,title,',
    //     'url' => 'required|max:80|regex:/^[a-z0-9-]+$/|unique:blogs,url,',
    //     'meta_description' => 'required|max:191|min:30',
    //     'image' => 'nullable|max:191|url',
    //     'canonical_url' => 'nullable|max:191|url',
    // ],
    'social_companies' => [
        'GOOGLE',
        'TWITTER',
        'FACEBOOK',
        'LINKEDIN',
        'GITHUB',
        'GITLAB',
        'BITBUCKET',
    ],
    'models' => [
        'factory' => [
            'address',
            'answer',
            'block',
            'blog',
            'car',
            'category',
            'cinema',
            'comment',
            'factor',
            'field',
            'food',
            'foodprogram',
            'form',
            'gym',
            'gymaction',
            'gymprogram',
            'home',
            'hotel',
            'module',
            'movie',
            'music',
            'page',
            'permission',
            'product',
            'restaurant',
            'role',
            'shop',
            'showtime',
            'tag',
            'tagend',
            'travel',
            'tour',
            'user',
        ],
        'seeder' => [
            'address',
            'answer',
            'blog',
            'car',
            'cinema',
            'factor',
            'field',
            'food',
            'food-program',
            'form',
            'gym',
            'gym-action',
            'gym-program',
            'home',
            'hotel',
            'movie',
            'music',
            'product',
            'restaurant',
            'shop',
            'showtime',
            'tagend',
            'travel',
            'tour',
        ],
        'front_routes' => [
            'answer',
            'blog',
            'car',
            'cinema',
            'food',
            'food-program',
            'gym',
            'gym-action',
            'gym-program',
            'home',
            'hotel',
            'movie',
            'music',
            'product',
            'restaurant',
            'shop',
            'showtime',
            'travel',
            'tour',
        ],
        'admin_routes' => [
            'activity',
            'answer',
            'address',
            'address',
            'block',
            'blog',
            'car',
            'category',
            'cinema',
            'comment',
            'factor',
            'field',
            'file',
            'follow',
            'food',
            'food-program',
            'form',
            'gym',
            'gym-action',
            'gym-program',
            'home',
            'hotel',
            'like',
            'media',
            'module',
            'movie',
            'music',
            'notification',
            'page',
            'permission',
            'product',
            'rate',
            'restaurant',
            'role',
            'shop',
            'showtime',
            'tag',
            'tagend',
            'tour',
            'travel',
            'user',
        ],
        'permissions' => [
            'activity',
            'answer',
            'address',
            'block',
            'blog',
            'car',
            'category',
            'cinema',
            'comment',
            'factor',
            'field',
            'file',
            'follow',
            'food',
            'food-program',
            'form',
            'gym',
            'gym-action',
            'gym-program',
            'home',
            'hotel',
            'like',
            'module',
            'movie',
            'music',
            'notification',
            'page',
            'permission',
            'product',
            'rate',
            'report',
            'restaurant',
            'role',
            'setting-general',
            'setting-contact',
            'setting-developer',
            'shop',
            'showtime',
            'tag',
            'tagend',
            'tour',
            'travel',
            'user',
        ],
    ],
];

foreach($output['social_companies'] as $social_company){
    $output[strtolower($social_company)] = [
        'client_id' => env($social_company . '_CLIENT_ID'),
        'client_secret' => env($social_company . '_CLIENT_SECRET'),
        'redirect' => env($social_company . '_CLIENT_CALLBACK'),
    ];
}

return $output;
